linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - godot
    - godox
    - gochecknoglobals
    - gofumpt
    - gomnd
    - gosec
    - ifshort
    - maligned
    - nestif
    - noctx
    - paralleltest
    - testpackage
    - usestdlibvars
    - wsl
