linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - gochecknoglobals
    - gosec
    - maligned
    - nestif
    - noctx
    - testpackage
    - wsl
